## Where the samples will be written
save_data: output/data

## Where the vocab(s) will be written
src_vocab:  output/vocab/source77.vocab_cluster.src
tgt_vocab: output/vocab/source77.vocab_cluster.src

## Where the model will be saved
save_model: model/cluster77_noaug
 
# Prevent overwriting existing files in the folder
overwrite: True
share_vocab: True
# Corpus opts:
data:
    corpus_1:
        path_src: preprocess/output/train_fp_FC2_r1_cutoff_0.6.sources.txt
        path_tgt: preprocess/output/train_fp_FC2_r1_cutoff_0.6.targets.txt
    valid:
        path_src: preprocess/output/valid_fp_FC2_r1_cutoff_0.6.sources.txt
        path_tgt: preprocess/output/valid_fp_FC2_r1_cutoff_0.6.targets.txt

world_size: 1
gpu_ranks: [0]

# Remove or modify these lines for bigger files
save_checkpoint_steps: 10000
keep_checkpoint: 20
seed: 42
train_steps: 100000
warmup_steps: 8000
report_every: 50000

decoder_type: transformer
encoder_type: transformer
word_vec_size: 256
rnn_size: 256
layers: 13
transformer_ff: 2048
heads: 8
decay_method: noam

accum_count: 4
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0

batch_size: 6144
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.0

max_generator_batches: 32

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'
share_embeddings: 'true'

global_attention: general
global_attention_function: softmax
self_attn_type: scaled-dot

world_size: 1
gpu_ranks:
- 0
